[package]
name = "alpines"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
serde_cbor = "0.11.2"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.sdl2]
version = "0.35.2"
